// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/deposit-redesign/Current.tsx": () => import("../components/mockups/deposit-redesign/Current.tsx"),
  "./components/mockups/deposit-redesign/New.tsx": () => import("../components/mockups/deposit-redesign/New.tsx")
};
